version: "3"
#version

# Déclaration des différents services

services:
  # Service React
  react-app:
    image: react-app
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app

  # Service api-server
  api-server:
    image: api-server
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo

   # Service mongodb
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
# Réseaux
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
